### ISSUE TITLE
I wanna show to many customers this game in my siteground

### ISSUE THREAD

**Issue by kjin9174** [FormidableLabs/react-game-kit#52]
I want i show to my customers in my hosting server.
My hosting server is siteground.

**Comment by ryan-roemer** [comment]
Hi @kjin9174 -- It's great that you're learning react game kit! Unfortunately, this GH issue board is best used for actual issues with the library. If you're just learning, best to head over to https://stackoverflow.com/ and maybe ask questions there.

Out of courtesy, we'll leave your https://github.com/FormidableLabs/react-game-kit/issues/51 open for a little while since it has discussion, but I'll be closing all your other issues so we can focus on development of this library.
