### ISSUE TITLE
Cannot read property 'subscribers' of undefined

### ISSUE THREAD

**Issue by sksahil030** [FormidableLabs/react-game-kit#56]
Getting the error - "Cannot read property 'subscribers' of undefined"

**Comment by sksahil030** [comment]
![screenshot_1513329980](https://user-images.githubusercontent.com/13555404/34035700-e6cb7a78-e1a8-11e7-9814-e87b29d5b454.png)

**Comment by iamlion** [comment]
react-native@0.33 + react-game-kit@0.0.1

**Comment by SYU15** [comment]
@sksahil030 are you using Expo? I am and am getting the same error, so I wondering if it is related? I was going to try and create a repo without it to see if that fixes the issue.

**Comment by filbertteo** [comment]
@SYU15 This bug is not related to Expo. It's a bug in this library.

I've made a PR that fixes this, hopefully it gets merged soon. In the meantime, if you need a quick workaround, modify `node_modules/react-game-kit/lib/native/utils/game-loop.js` as follows:
1. add `this.loop = this.loop.bind(this);` after line 16 `this.loopID = null;`
2. optionally, change line 42 from `this.subscribers.splice((id - 1), 1);` to `delete this.subscribers[id - 1];`. This will help prevent an app crash if you have more than 1 subscriber to the game loop, assuming you handle the subscribe/unsubscribe properly
