### ISSUE TITLE
Archived? Whats the future on this?

### ISSUE THREAD

**Issue by timothymarois** [FormidableLabs/react-game-kit#82]
Can someone explain why the maintenance says its archived, this repo hasn't been updated in years, and want to know if there is something better that has replaced this or was it just not worth running with this any longer?

**Comment by IceOnFire** [comment]
Hi @timothymarois,

I just finished a painstaking port to React 17 with hooks and Context API. You can check it  [here](https://github.com/IngloriousCoderz/react-game-kit).

The bottom line of my experiment is that there are lots of things changing in a game at the same time: some of them should trigger a re-render, some of them should not, and some of them should but don't so we have to find workarounds. This is due to the fact that re-renders are subject to changes from a global state (e.g. the player's position), some local states (e.g. the current animation frame), a game loop with subscribers listening, a physics engine with subscribers listening, ...

Maybe the project could benefit more from a global state manager such as Redux, with all async updates managed in sagas, but still, I'm not sure if it's worth the while. I wanted to reuse this code to experiment with some game AI algorithms, but then I moved to the [Godot Engine](https://godotengine.org/) so I was able to achieve something without too much hassle and focusing on the things that mattered to me.

Feel free anyway to review my port and maybe we could improve it together!

**Comment by timothymarois** [comment]
@IceOnFire Got it. thanks for the response. Do you like the Godot engine? I was starting to use Unity, but for just a 2d game and simplicity sake, I'm thinking of switching to Godot, any reason you think I should or shouldnt? Sorry off-topic, just curious your opinion to it.

**Comment by IceOnFire** [comment]
I don't know much about game engines, but I love Godot's component-based approach (very similar to React's) and the GDScript language, which is a Python on steroids. But I'm still a total newbie and still dreaming of a React-based game engine...

**Comment by timothymarois** [comment]
@IceOnFire Thanks! I will be looking more into Godot when I get the chance, so far I do love the UI much more than Unity. Anyways, I'll close this.
